Name: pulseaudio-settings-n900
Summary: PulseAudio settings for Nokia N900
Version: 4.0.4
Release: 1
Group: System/Libraries
License: GPLv2
URL: https://github.com/nemomobile/pulseaudio-settings-n900
Description: |
    PulseAudio settings for Nokia N900
BuildArch: noarch

Sources:
    - "%{name}-%{version}.tar.gz"

Configure: none
Builder: none

Requires:
    - pulseaudio >= 4.0
    - pulseaudio-modules-nemo-music >= 4.0.4
    - pulseaudio-modules-nemo-record >= 4.0.4
    - pulseaudio-modules-nemo-stream-restore >= 4.0.4
    - pulseaudio-modules-nemo-voice >= 4.0.4
    - pulseaudio-module-cmtspeech-n9xx >= 4.0.3
    - pulseaudio-policy-enforcement

# The closed Nokia modules are not compatible with pulseaudio 2.1/4.0. Obsoleting
# them here in the settings package should make the upgrade from 0.9.22 to 2.1
# go smoothly without complaints from the package manager.
Obsoletes:
    - pulseaudio-modules-nokia-common-bin
    - pulseaudio-modules-nokia-algorithms-bin
    - pulseaudio-modules-nokia-audiots-bin
    - pulseaudio-modules-nokia-parameters-bin
